// <auto-generated />
using System;
using FanucRelease.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FanucRelease.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250826064839_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FanucRelease.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("FanucRelease.Models.AnlikKaynak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amper")
                        .HasColumnType("float");

                    b.Property<int>("KaynakHizi")
                        .HasColumnType("int");

                    b.Property<int>("KaynakId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlcumZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProgramSatiri")
                        .HasColumnType("int");

                    b.Property<double>("TelSurmeHizi")
                        .HasColumnType("float");

                    b.Property<double>("Voltaj")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("KaynakId");

                    b.ToTable("AnlikKaynaklar");
                });

            modelBuilder.Entity("FanucRelease.Models.Kaynak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<int>("BaslangicSatiri")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<int>("BitisSatiri")
                        .HasColumnType("int");

                    b.Property<double?>("ToplamSureSaniye")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Kaynaklar");
                });

            modelBuilder.Entity("FanucRelease.Models.KaynakParametre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amper")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KaynakId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OlcumZamani")
                        .HasColumnType("time");

                    b.Property<decimal>("TelSurmeHizi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Voltaj")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KaynakId");

                    b.ToTable("KaynakParametreleri");
                });

            modelBuilder.Entity("FanucRelease.Models.MakineDurus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<int>("KaynakId")
                        .HasColumnType("int");

                    b.Property<string>("Sebep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KaynakId");

                    b.ToTable("MakineDuruslari");
                });

            modelBuilder.Entity("FanucRelease.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("FanucRelease.Models.TrafoBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KaynakId")
                        .HasColumnType("int");

                    b.Property<string>("TrafoAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KaynakId");

                    b.ToTable("TrafoBilgileri");
                });

            modelBuilder.Entity("ProgramVerisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HataKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KaynakId")
                        .HasColumnType("int");

                    b.Property<int>("KaynakSayisi")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KaynakId");

                    b.HasIndex("OperatorId");

                    b.ToTable("RobotVerileri");
                });

            modelBuilder.Entity("FanucRelease.Models.AnlikKaynak", b =>
                {
                    b.HasOne("FanucRelease.Models.Kaynak", "Kaynak")
                        .WithMany("AnlikKaynaklar")
                        .HasForeignKey("KaynakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kaynak");
                });

            modelBuilder.Entity("FanucRelease.Models.KaynakParametre", b =>
                {
                    b.HasOne("FanucRelease.Models.Kaynak", "Kaynak")
                        .WithMany()
                        .HasForeignKey("KaynakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kaynak");
                });

            modelBuilder.Entity("FanucRelease.Models.MakineDurus", b =>
                {
                    b.HasOne("FanucRelease.Models.Kaynak", "Kaynak")
                        .WithMany()
                        .HasForeignKey("KaynakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kaynak");
                });

            modelBuilder.Entity("FanucRelease.Models.TrafoBilgisi", b =>
                {
                    b.HasOne("FanucRelease.Models.Kaynak", "Kaynak")
                        .WithMany()
                        .HasForeignKey("KaynakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kaynak");
                });

            modelBuilder.Entity("ProgramVerisi", b =>
                {
                    b.HasOne("FanucRelease.Models.Kaynak", "Kaynak")
                        .WithMany()
                        .HasForeignKey("KaynakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FanucRelease.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kaynak");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("FanucRelease.Models.Kaynak", b =>
                {
                    b.Navigation("AnlikKaynaklar");
                });
#pragma warning restore 612, 618
        }
    }
}
