// <auto-generated />
using System;
using FanucRelease.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FanucRelease.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250722143043_IlkYapi")]
    partial class IlkYapi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FanucRelease.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("FanucRelease.Models.KaynakDongusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("bit");

                    b.Property<double?>("ToplamSureSaniye")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("KaynakDonguleri");
                });

            modelBuilder.Entity("FanucRelease.Models.KaynakParametre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amper")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KaynakDongusuId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OlcumZamani")
                        .HasColumnType("time");

                    b.Property<decimal>("TelSurmeHizi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Voltaj")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KaynakDongusuId");

                    b.ToTable("KaynakParametreleri");
                });

            modelBuilder.Entity("FanucRelease.Models.MakineDurus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<int>("KaynakDongusuId")
                        .HasColumnType("int");

                    b.Property<string>("Sebep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KaynakDongusuId");

                    b.ToTable("MakineDuruslari");
                });

            modelBuilder.Entity("FanucRelease.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("FanucRelease.Models.TrafoBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KaynakDongusuId")
                        .HasColumnType("int");

                    b.Property<string>("TrafoAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KaynakDongusuId");

                    b.ToTable("TrafoBilgileri");
                });

            modelBuilder.Entity("FanucRelease.Models.KaynakDongusu", b =>
                {
                    b.HasOne("FanucRelease.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("FanucRelease.Models.KaynakParametre", b =>
                {
                    b.HasOne("FanucRelease.Models.KaynakDongusu", "KaynakDongusu")
                        .WithMany()
                        .HasForeignKey("KaynakDongusuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KaynakDongusu");
                });

            modelBuilder.Entity("FanucRelease.Models.MakineDurus", b =>
                {
                    b.HasOne("FanucRelease.Models.KaynakDongusu", "KaynakDongusu")
                        .WithMany()
                        .HasForeignKey("KaynakDongusuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KaynakDongusu");
                });

            modelBuilder.Entity("FanucRelease.Models.TrafoBilgisi", b =>
                {
                    b.HasOne("FanucRelease.Models.KaynakDongusu", "KaynakDongusu")
                        .WithMany()
                        .HasForeignKey("KaynakDongusuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KaynakDongusu");
                });
#pragma warning restore 612, 618
        }
    }
}
