// <auto-generated />
using System;
using FanucRelease.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FanucRelease.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250919070051_AddTarihToProgramVerisi")]
    partial class AddTarihToProgramVerisi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FanucRelease.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("FanucRelease.Models.AnlikKaynak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amper")
                        .HasColumnType("float");

                    b.Property<int>("KaynakHizi")
                        .HasColumnType("int");

                    b.Property<int>("KaynakId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlcumZamani")
                        .HasColumnType("datetime2");

                    b.Property<double>("TelSurmeHizi")
                        .HasColumnType("float");

                    b.Property<double>("Voltaj")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("KaynakId");

                    b.ToTable("AnlikKaynaklar");
                });

            modelBuilder.Entity("FanucRelease.Models.Hata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgramVerisiId")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<DateTime>("Zaman")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProgramVerisiId");

                    b.ToTable("Hatalar");
                });

            modelBuilder.Entity("FanucRelease.Models.Kaynak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicSaati")
                        .HasColumnType("datetime2");

                    b.Property<int>("BaslangicSatiri")
                        .HasColumnType("int");

                    b.Property<DateTime>("BitisSaati")
                        .HasColumnType("datetime2");

                    b.Property<int>("BitisSatiri")
                        .HasColumnType("int");

                    b.Property<int>("KaynakUzunlugu")
                        .HasColumnType("int");

                    b.Property<int>("PrcNo")
                        .HasColumnType("int");

                    b.Property<int>("ProgramVerisiId")
                        .HasColumnType("int");

                    b.Property<int>("SrcNo")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ToplamSure")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ProgramVerisiId");

                    b.ToTable("Kaynaklar");
                });

            modelBuilder.Entity("FanucRelease.Models.KaynakParametre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amper")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KaynakId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OlcumZamani")
                        .HasColumnType("time");

                    b.Property<decimal>("TelSurmeHizi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Voltaj")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KaynakId");

                    b.ToTable("KaynakParametreleri");
                });

            modelBuilder.Entity("FanucRelease.Models.MakineDurus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<int>("KaynakId")
                        .HasColumnType("int");

                    b.Property<string>("Sebep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KaynakId");

                    b.ToTable("MakineDuruslari");
                });

            modelBuilder.Entity("FanucRelease.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("FanucRelease.Models.ProgramVerisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KaynakSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("ProgramVerileri");
                });

            modelBuilder.Entity("FanucRelease.Models.TrafoBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KaynakId")
                        .HasColumnType("int");

                    b.Property<string>("TrafoAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KaynakId");

                    b.ToTable("TrafoBilgileri");
                });

            modelBuilder.Entity("Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RobotIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RobotPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RobotUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SqlIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SqlPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SqlUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrustServerCertificate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("FanucRelease.Models.AnlikKaynak", b =>
                {
                    b.HasOne("FanucRelease.Models.Kaynak", "Kaynak")
                        .WithMany("AnlikKaynaklar")
                        .HasForeignKey("KaynakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kaynak");
                });

            modelBuilder.Entity("FanucRelease.Models.Hata", b =>
                {
                    b.HasOne("FanucRelease.Models.ProgramVerisi", null)
                        .WithMany("Hatalar")
                        .HasForeignKey("ProgramVerisiId");
                });

            modelBuilder.Entity("FanucRelease.Models.Kaynak", b =>
                {
                    b.HasOne("FanucRelease.Models.ProgramVerisi", "ProgramVerisi")
                        .WithMany("Kaynaklar")
                        .HasForeignKey("ProgramVerisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramVerisi");
                });

            modelBuilder.Entity("FanucRelease.Models.KaynakParametre", b =>
                {
                    b.HasOne("FanucRelease.Models.Kaynak", "Kaynak")
                        .WithMany()
                        .HasForeignKey("KaynakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kaynak");
                });

            modelBuilder.Entity("FanucRelease.Models.MakineDurus", b =>
                {
                    b.HasOne("FanucRelease.Models.Kaynak", "Kaynak")
                        .WithMany()
                        .HasForeignKey("KaynakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kaynak");
                });

            modelBuilder.Entity("FanucRelease.Models.ProgramVerisi", b =>
                {
                    b.HasOne("FanucRelease.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("FanucRelease.Models.TrafoBilgisi", b =>
                {
                    b.HasOne("FanucRelease.Models.Kaynak", "Kaynak")
                        .WithMany()
                        .HasForeignKey("KaynakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kaynak");
                });

            modelBuilder.Entity("FanucRelease.Models.Kaynak", b =>
                {
                    b.Navigation("AnlikKaynaklar");
                });

            modelBuilder.Entity("FanucRelease.Models.ProgramVerisi", b =>
                {
                    b.Navigation("Hatalar");

                    b.Navigation("Kaynaklar");
                });
#pragma warning restore 612, 618
        }
    }
}
